--
-- PostgreSQL database dump
--

\restrict GA5XmqRpNxusDLNZ6KN4na1wQRllhxgjh64zur3sdMvORVMD0b1bsE4hpPJc5uS

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4 (Debian 18.4-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vdl_postgresql_001; Type: SCHEMA; Schema: -; Owner: vdlgoluanuj
--

CREATE SCHEMA vdl_postgresql_001;


ALTER SCHEMA vdl_postgresql_001 OWNER TO vdlgoluanuj;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: WeatherForecasts; Type: TABLE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE TABLE vdl_postgresql_001."WeatherForecasts" (
    "Id" integer NOT NULL,
    "Date" date NOT NULL,
    "TemperatureC" integer NOT NULL,
    "Summary" character varying(50)
);


ALTER TABLE vdl_postgresql_001."WeatherForecasts" OWNER TO vdlgoluanuj;

--
-- Name: WeatherForecasts_Id_seq; Type: SEQUENCE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE vdl_postgresql_001."WeatherForecasts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME vdl_postgresql_001."WeatherForecasts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: endpoint_permissions; Type: TABLE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE TABLE vdl_postgresql_001.endpoint_permissions (
    "Id" integer NOT NULL,
    "RouteUrl" text NOT NULL,
    "HttpMethod" text NOT NULL,
    "RoleId" integer NOT NULL,
    "CreatedBy" text
);


ALTER TABLE vdl_postgresql_001.endpoint_permissions OWNER TO vdlgoluanuj;

--
-- Name: endpoint_permissions_Id_seq; Type: SEQUENCE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE vdl_postgresql_001.endpoint_permissions ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME vdl_postgresql_001."endpoint_permissions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fee_payments; Type: TABLE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE TABLE vdl_postgresql_001.fee_payments (
    "Id" integer NOT NULL,
    "FeeRecordId" integer NOT NULL,
    "AmountPaid" numeric(10,2) NOT NULL,
    "PaymentDate" timestamp with time zone NOT NULL,
    "PaymentMode" character varying(50) NOT NULL,
    "CollectedBy" text,
    "Note" text,
    "CreatedDate" timestamp with time zone NOT NULL
);


ALTER TABLE vdl_postgresql_001.fee_payments OWNER TO vdlgoluanuj;

--
-- Name: fee_payments_Id_seq; Type: SEQUENCE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE vdl_postgresql_001.fee_payments ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME vdl_postgresql_001."fee_payments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fee_records; Type: TABLE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE TABLE vdl_postgresql_001.fee_records (
    "Id" integer NOT NULL,
    "VdlId" character varying(50) NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "TotalFee" numeric(10,2) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "Description" text,
    "CreatedBy" text,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone NOT NULL
);


ALTER TABLE vdl_postgresql_001.fee_records OWNER TO vdlgoluanuj;

--
-- Name: fee_records_Id_seq; Type: SEQUENCE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE vdl_postgresql_001.fee_records ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME vdl_postgresql_001."fee_records_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE TABLE vdl_postgresql_001.roles (
    "RoleSequenceId" integer NOT NULL,
    "RoleName" character varying(100) NOT NULL,
    "RoleId" integer NOT NULL,
    "CreatedBy" text
);


ALTER TABLE vdl_postgresql_001.roles OWNER TO vdlgoluanuj;

--
-- Name: roles_RoleSequenceId_seq; Type: SEQUENCE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE vdl_postgresql_001.roles ALTER COLUMN "RoleSequenceId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME vdl_postgresql_001."roles_RoleSequenceId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seat_assignments; Type: TABLE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE TABLE vdl_postgresql_001.seat_assignments (
    "Id" integer NOT NULL,
    "SeatId" integer NOT NULL,
    "ShiftId" integer NOT NULL,
    "StudentId" integer NOT NULL,
    "CreatedBy" text,
    "IsDeleted" boolean DEFAULT false NOT NULL,
    "AssignedDate" timestamp with time zone NOT NULL,
    "RemovedDate" timestamp with time zone
);


ALTER TABLE vdl_postgresql_001.seat_assignments OWNER TO vdlgoluanuj;

--
-- Name: seat_assignments_Id_seq; Type: SEQUENCE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE vdl_postgresql_001.seat_assignments ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME vdl_postgresql_001."seat_assignments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seat_rows; Type: TABLE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE TABLE vdl_postgresql_001.seat_rows (
    "Id" integer NOT NULL,
    "RowName" character varying(100) NOT NULL,
    "RowOrder" integer NOT NULL,
    "IsLocked" boolean DEFAULT false NOT NULL,
    "IsDeleted" boolean DEFAULT false NOT NULL,
    "CreatedBy" text,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedBy" text,
    "UpdatedDate" timestamp with time zone NOT NULL
);


ALTER TABLE vdl_postgresql_001.seat_rows OWNER TO vdlgoluanuj;

--
-- Name: seat_rows_Id_seq; Type: SEQUENCE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE vdl_postgresql_001.seat_rows ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME vdl_postgresql_001."seat_rows_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seats; Type: TABLE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE TABLE vdl_postgresql_001.seats (
    "Id" integer NOT NULL,
    "SeatRowId" integer NOT NULL,
    "SeatLabel" character varying(50) NOT NULL,
    "SeatOrder" integer NOT NULL,
    "IsLocked" boolean DEFAULT false NOT NULL,
    "IsDeleted" boolean DEFAULT false NOT NULL,
    "CreatedBy" text,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedBy" text,
    "UpdatedDate" timestamp with time zone NOT NULL
);


ALTER TABLE vdl_postgresql_001.seats OWNER TO vdlgoluanuj;

--
-- Name: seats_Id_seq; Type: SEQUENCE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE vdl_postgresql_001.seats ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME vdl_postgresql_001."seats_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shifts; Type: TABLE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE TABLE vdl_postgresql_001.shifts (
    "Id" integer NOT NULL,
    "ShiftName" character varying(100) NOT NULL,
    "Status" integer DEFAULT 1 NOT NULL,
    "StartTime" interval,
    "EndTime" interval,
    "CreatedBy" text NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedBy" text,
    "UpdatedDate" timestamp with time zone NOT NULL,
    "IsDeleted" boolean DEFAULT false NOT NULL
);


ALTER TABLE vdl_postgresql_001.shifts OWNER TO vdlgoluanuj;

--
-- Name: shifts_Id_seq; Type: SEQUENCE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE vdl_postgresql_001.shifts ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME vdl_postgresql_001."shifts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: statuses; Type: TABLE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE TABLE vdl_postgresql_001.statuses (
    "Id" integer NOT NULL,
    "StatusId" integer NOT NULL,
    "StatusType" character varying(50) NOT NULL,
    "StatusName" character varying(50) NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL
);


ALTER TABLE vdl_postgresql_001.statuses OWNER TO vdlgoluanuj;

--
-- Name: statuses_Id_seq; Type: SEQUENCE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE vdl_postgresql_001.statuses ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME vdl_postgresql_001."statuses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_details; Type: TABLE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE TABLE vdl_postgresql_001.student_details (
    "Id" integer NOT NULL,
    "VdlId" character varying(50) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "FatherName" character varying(100),
    "Gender" character varying(20),
    "SeatNumber" integer,
    "ShiftType" character varying(50),
    "Address" character varying(255),
    "AlternateNumber" character varying(20),
    "Class" character varying(50),
    "DateOfBirth" timestamp with time zone,
    "IdProof" character varying(100),
    "MobileNumber" character varying(20),
    "StudentStatus" character varying(50),
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" text
);


ALTER TABLE vdl_postgresql_001.student_details OWNER TO vdlgoluanuj;

--
-- Name: student_details_Id_seq; Type: SEQUENCE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE vdl_postgresql_001.student_details ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME vdl_postgresql_001."student_details_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE TABLE vdl_postgresql_001.users (
    "Id" integer NOT NULL,
    "Username" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "MobileNumber" character varying(20),
    "PasswordHash" text NOT NULL,
    "RoleId" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "IsPasswordChangedFromTemp" boolean NOT NULL,
    "TenantId" text NOT NULL
);


ALTER TABLE vdl_postgresql_001.users OWNER TO vdlgoluanuj;

--
-- Name: users_Id_seq; Type: SEQUENCE; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE vdl_postgresql_001.users ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME vdl_postgresql_001."users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: WeatherForecasts; Type: TABLE DATA; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

COPY vdl_postgresql_001."WeatherForecasts" ("Id", "Date", "TemperatureC", "Summary") FROM stdin;
\.


--
-- Data for Name: endpoint_permissions; Type: TABLE DATA; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

COPY vdl_postgresql_001.endpoint_permissions ("Id", "RouteUrl", "HttpMethod", "RoleId", "CreatedBy") FROM stdin;
\.


--
-- Data for Name: fee_payments; Type: TABLE DATA; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

COPY vdl_postgresql_001.fee_payments ("Id", "FeeRecordId", "AmountPaid", "PaymentDate", "PaymentMode", "CollectedBy", "Note", "CreatedDate") FROM stdin;
\.


--
-- Data for Name: fee_records; Type: TABLE DATA; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

COPY vdl_postgresql_001.fee_records ("Id", "VdlId", "StartDate", "EndDate", "TotalFee", "Status", "Description", "CreatedBy", "CreatedDate", "UpdatedDate") FROM stdin;
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

COPY vdl_postgresql_001.roles ("RoleSequenceId", "RoleName", "RoleId", "CreatedBy") FROM stdin;
1	Admin	1	\N
2	Internal User	2	\N
3	External User	3	\N
4	Student	4	\N
\.


--
-- Data for Name: seat_assignments; Type: TABLE DATA; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

COPY vdl_postgresql_001.seat_assignments ("Id", "SeatId", "ShiftId", "StudentId", "CreatedBy", "IsDeleted", "AssignedDate", "RemovedDate") FROM stdin;
\.


--
-- Data for Name: seat_rows; Type: TABLE DATA; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

COPY vdl_postgresql_001.seat_rows ("Id", "RowName", "RowOrder", "IsLocked", "IsDeleted", "CreatedBy", "CreatedDate", "UpdatedBy", "UpdatedDate") FROM stdin;
\.


--
-- Data for Name: seats; Type: TABLE DATA; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

COPY vdl_postgresql_001.seats ("Id", "SeatRowId", "SeatLabel", "SeatOrder", "IsLocked", "IsDeleted", "CreatedBy", "CreatedDate", "UpdatedBy", "UpdatedDate") FROM stdin;
\.


--
-- Data for Name: shifts; Type: TABLE DATA; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

COPY vdl_postgresql_001.shifts ("Id", "ShiftName", "Status", "StartTime", "EndTime", "CreatedBy", "CreatedDate", "UpdatedBy", "UpdatedDate", "IsDeleted") FROM stdin;
\.


--
-- Data for Name: statuses; Type: TABLE DATA; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

COPY vdl_postgresql_001.statuses ("Id", "StatusId", "StatusType", "StatusName", "IsActive") FROM stdin;
1	1	Fee	Pending	t
2	2	Fee	Partial	t
3	3	Fee	Paid	t
4	4	General	Active	t
5	5	General	Not Active	t
6	6	Student	Active	t
7	7	Student	Not Active	t
8	8	Student	Dropped	t
9	9	Student	Cancelled	t
\.


--
-- Data for Name: student_details; Type: TABLE DATA; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

COPY vdl_postgresql_001.student_details ("Id", "VdlId", "Name", "Email", "FatherName", "Gender", "SeatNumber", "ShiftType", "Address", "AlternateNumber", "Class", "DateOfBirth", "IdProof", "MobileNumber", "StudentStatus", "CreatedDate", "UpdatedDate", "CreatedBy") FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

COPY vdl_postgresql_001.users ("Id", "Username", "Email", "MobileNumber", "PasswordHash", "RoleId", "IsActive", "CreatedDate", "UpdatedDate", "CreatedBy", "IsPasswordChangedFromTemp", "TenantId") FROM stdin;
1	vdl_postgresql_001_admin	admin@vdl_postgresql_001.com	\N	$2a$11$/AUxSEyomIMWdzkq/y3wd.QMcsIPjc1HDGRYxCVSbUskQHcczSrHK	1	t	2026-06-01 11:21:48.75636+00	2026-06-01 11:21:48.756361+00	\N	f	vdl_postgresql_001
\.


--
-- Name: WeatherForecasts_Id_seq; Type: SEQUENCE SET; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

SELECT pg_catalog.setval('vdl_postgresql_001."WeatherForecasts_Id_seq"', 1, false);


--
-- Name: endpoint_permissions_Id_seq; Type: SEQUENCE SET; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

SELECT pg_catalog.setval('vdl_postgresql_001."endpoint_permissions_Id_seq"', 1, false);


--
-- Name: fee_payments_Id_seq; Type: SEQUENCE SET; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

SELECT pg_catalog.setval('vdl_postgresql_001."fee_payments_Id_seq"', 1, false);


--
-- Name: fee_records_Id_seq; Type: SEQUENCE SET; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

SELECT pg_catalog.setval('vdl_postgresql_001."fee_records_Id_seq"', 1, false);


--
-- Name: roles_RoleSequenceId_seq; Type: SEQUENCE SET; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

SELECT pg_catalog.setval('vdl_postgresql_001."roles_RoleSequenceId_seq"', 4, true);


--
-- Name: seat_assignments_Id_seq; Type: SEQUENCE SET; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

SELECT pg_catalog.setval('vdl_postgresql_001."seat_assignments_Id_seq"', 1, false);


--
-- Name: seat_rows_Id_seq; Type: SEQUENCE SET; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

SELECT pg_catalog.setval('vdl_postgresql_001."seat_rows_Id_seq"', 1, false);


--
-- Name: seats_Id_seq; Type: SEQUENCE SET; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

SELECT pg_catalog.setval('vdl_postgresql_001."seats_Id_seq"', 1, false);


--
-- Name: shifts_Id_seq; Type: SEQUENCE SET; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

SELECT pg_catalog.setval('vdl_postgresql_001."shifts_Id_seq"', 1, false);


--
-- Name: statuses_Id_seq; Type: SEQUENCE SET; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

SELECT pg_catalog.setval('vdl_postgresql_001."statuses_Id_seq"', 10, false);


--
-- Name: student_details_Id_seq; Type: SEQUENCE SET; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

SELECT pg_catalog.setval('vdl_postgresql_001."student_details_Id_seq"', 1, false);


--
-- Name: users_Id_seq; Type: SEQUENCE SET; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

SELECT pg_catalog.setval('vdl_postgresql_001."users_Id_seq"', 1, true);


--
-- Name: roles AK_roles_RoleId; Type: CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.roles
    ADD CONSTRAINT "AK_roles_RoleId" UNIQUE ("RoleId");


--
-- Name: student_details AK_student_details_VdlId; Type: CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.student_details
    ADD CONSTRAINT "AK_student_details_VdlId" UNIQUE ("VdlId");


--
-- Name: WeatherForecasts PK_WeatherForecasts; Type: CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001."WeatherForecasts"
    ADD CONSTRAINT "PK_WeatherForecasts" PRIMARY KEY ("Id");


--
-- Name: endpoint_permissions PK_endpoint_permissions; Type: CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.endpoint_permissions
    ADD CONSTRAINT "PK_endpoint_permissions" PRIMARY KEY ("Id");


--
-- Name: fee_payments PK_fee_payments; Type: CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.fee_payments
    ADD CONSTRAINT "PK_fee_payments" PRIMARY KEY ("Id");


--
-- Name: fee_records PK_fee_records; Type: CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.fee_records
    ADD CONSTRAINT "PK_fee_records" PRIMARY KEY ("Id");


--
-- Name: roles PK_roles; Type: CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.roles
    ADD CONSTRAINT "PK_roles" PRIMARY KEY ("RoleSequenceId");


--
-- Name: seat_assignments PK_seat_assignments; Type: CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.seat_assignments
    ADD CONSTRAINT "PK_seat_assignments" PRIMARY KEY ("Id");


--
-- Name: seat_rows PK_seat_rows; Type: CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.seat_rows
    ADD CONSTRAINT "PK_seat_rows" PRIMARY KEY ("Id");


--
-- Name: seats PK_seats; Type: CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.seats
    ADD CONSTRAINT "PK_seats" PRIMARY KEY ("Id");


--
-- Name: shifts PK_shifts; Type: CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.shifts
    ADD CONSTRAINT "PK_shifts" PRIMARY KEY ("Id");


--
-- Name: statuses PK_statuses; Type: CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.statuses
    ADD CONSTRAINT "PK_statuses" PRIMARY KEY ("Id");


--
-- Name: student_details PK_student_details; Type: CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.student_details
    ADD CONSTRAINT "PK_student_details" PRIMARY KEY ("Id");


--
-- Name: users PK_users; Type: CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.users
    ADD CONSTRAINT "PK_users" PRIMARY KEY ("Id");


--
-- Name: IX_fee_payments_FeeRecordId; Type: INDEX; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE INDEX "IX_fee_payments_FeeRecordId" ON vdl_postgresql_001.fee_payments USING btree ("FeeRecordId");


--
-- Name: IX_fee_records_VdlId; Type: INDEX; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE INDEX "IX_fee_records_VdlId" ON vdl_postgresql_001.fee_records USING btree ("VdlId");


--
-- Name: IX_roles_RoleId; Type: INDEX; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE UNIQUE INDEX "IX_roles_RoleId" ON vdl_postgresql_001.roles USING btree ("RoleId");


--
-- Name: IX_seat_assignments_SeatId; Type: INDEX; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE INDEX "IX_seat_assignments_SeatId" ON vdl_postgresql_001.seat_assignments USING btree ("SeatId");


--
-- Name: IX_seat_assignments_ShiftId; Type: INDEX; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE INDEX "IX_seat_assignments_ShiftId" ON vdl_postgresql_001.seat_assignments USING btree ("ShiftId");


--
-- Name: IX_seat_assignments_StudentId; Type: INDEX; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE INDEX "IX_seat_assignments_StudentId" ON vdl_postgresql_001.seat_assignments USING btree ("StudentId");


--
-- Name: IX_seats_SeatRowId; Type: INDEX; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE INDEX "IX_seats_SeatRowId" ON vdl_postgresql_001.seats USING btree ("SeatRowId");


--
-- Name: IX_shifts_ShiftName; Type: INDEX; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE UNIQUE INDEX "IX_shifts_ShiftName" ON vdl_postgresql_001.shifts USING btree ("ShiftName");


--
-- Name: IX_statuses_StatusType_StatusName; Type: INDEX; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE UNIQUE INDEX "IX_statuses_StatusType_StatusName" ON vdl_postgresql_001.statuses USING btree ("StatusType", "StatusName");


--
-- Name: IX_users_MobileNumber; Type: INDEX; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE UNIQUE INDEX "IX_users_MobileNumber" ON vdl_postgresql_001.users USING btree ("MobileNumber");


--
-- Name: IX_users_RoleId; Type: INDEX; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

CREATE INDEX "IX_users_RoleId" ON vdl_postgresql_001.users USING btree ("RoleId");


--
-- Name: fee_payments FK_fee_payments_fee_records_FeeRecordId; Type: FK CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.fee_payments
    ADD CONSTRAINT "FK_fee_payments_fee_records_FeeRecordId" FOREIGN KEY ("FeeRecordId") REFERENCES vdl_postgresql_001.fee_records("Id") ON DELETE CASCADE;


--
-- Name: fee_records FK_fee_records_student_details_VdlId; Type: FK CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.fee_records
    ADD CONSTRAINT "FK_fee_records_student_details_VdlId" FOREIGN KEY ("VdlId") REFERENCES vdl_postgresql_001.student_details("VdlId") ON DELETE CASCADE;


--
-- Name: seat_assignments FK_seat_assignments_seats_SeatId; Type: FK CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.seat_assignments
    ADD CONSTRAINT "FK_seat_assignments_seats_SeatId" FOREIGN KEY ("SeatId") REFERENCES vdl_postgresql_001.seats("Id") ON DELETE CASCADE;


--
-- Name: seat_assignments FK_seat_assignments_shifts_ShiftId; Type: FK CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.seat_assignments
    ADD CONSTRAINT "FK_seat_assignments_shifts_ShiftId" FOREIGN KEY ("ShiftId") REFERENCES vdl_postgresql_001.shifts("Id") ON DELETE CASCADE;


--
-- Name: seat_assignments FK_seat_assignments_student_details_StudentId; Type: FK CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.seat_assignments
    ADD CONSTRAINT "FK_seat_assignments_student_details_StudentId" FOREIGN KEY ("StudentId") REFERENCES vdl_postgresql_001.student_details("Id") ON DELETE CASCADE;


--
-- Name: seats FK_seats_seat_rows_SeatRowId; Type: FK CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.seats
    ADD CONSTRAINT "FK_seats_seat_rows_SeatRowId" FOREIGN KEY ("SeatRowId") REFERENCES vdl_postgresql_001.seat_rows("Id") ON DELETE CASCADE;


--
-- Name: users FK_users_roles_RoleId; Type: FK CONSTRAINT; Schema: vdl_postgresql_001; Owner: vdlgoluanuj
--

ALTER TABLE ONLY vdl_postgresql_001.users
    ADD CONSTRAINT "FK_users_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES vdl_postgresql_001.roles("RoleId") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict GA5XmqRpNxusDLNZ6KN4na1wQRllhxgjh64zur3sdMvORVMD0b1bsE4hpPJc5uS

