// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vdlcrm.Services;

#nullable disable

namespace Vdlcrm.Services.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507220547_CompleteStringConversionFix1")]
    partial class CompleteStringConversionFix1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Vdlcrm.Model.AppStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StatusType", "StatusName")
                        .IsUnique();

                    b.ToTable("statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            StatusId = 1,
                            StatusName = "Pending",
                            StatusType = "Fee"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            StatusId = 2,
                            StatusName = "Partial",
                            StatusType = "Fee"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            StatusId = 3,
                            StatusName = "Paid",
                            StatusType = "Fee"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            StatusId = 4,
                            StatusName = "Active",
                            StatusType = "General"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            StatusId = 5,
                            StatusName = "Not Active",
                            StatusType = "General"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            StatusId = 6,
                            StatusName = "Active",
                            StatusType = "Student"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            StatusId = 7,
                            StatusName = "Not Active",
                            StatusType = "Student"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            StatusId = 8,
                            StatusName = "Dropped",
                            StatusType = "Student"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            StatusId = 9,
                            StatusName = "Cancelled",
                            StatusType = "Student"
                        });
                });

            modelBuilder.Entity("Vdlcrm.Model.EndpointPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RouteUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("endpoint_permissions", (string)null);
                });

            modelBuilder.Entity("Vdlcrm.Model.FeePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CollectedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeeRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeeRecordId");

                    b.ToTable("fee_payments", (string)null);
                });

            modelBuilder.Entity("Vdlcrm.Model.FeeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VdlId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VdlId");

                    b.ToTable("fee_records", (string)null);
                });

            modelBuilder.Entity("Vdlcrm.Model.Role", b =>
                {
                    b.Property<int>("RoleSequenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleSequenceId");

                    b.HasIndex("RoleId")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Vdlcrm.Model.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("EndTime")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("StartTime")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShiftName")
                        .IsUnique();

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("Vdlcrm.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<string>("AlternateNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<string>("Class")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(15);

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("FatherName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("IdProof")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<int?>("SeatNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(6);

                    b.Property<string>("ShiftType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<string>("StudentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(14);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(16);

                    b.Property<string>("VdlId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("student_details", (string)null);
                });

            modelBuilder.Entity("Vdlcrm.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPasswordChangedFromTemp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Vdlcrm.Model.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("Vdlcrm.Model.FeePayment", b =>
                {
                    b.HasOne("Vdlcrm.Model.FeeRecord", "FeeRecord")
                        .WithMany("FeePayments")
                        .HasForeignKey("FeeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeRecord");
                });

            modelBuilder.Entity("Vdlcrm.Model.FeeRecord", b =>
                {
                    b.HasOne("Vdlcrm.Model.Student", "Student")
                        .WithMany()
                        .HasForeignKey("VdlId")
                        .HasPrincipalKey("VdlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Vdlcrm.Model.User", b =>
                {
                    b.HasOne("Vdlcrm.Model.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasPrincipalKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Vdlcrm.Model.FeeRecord", b =>
                {
                    b.Navigation("FeePayments");
                });
#pragma warning restore 612, 618
        }
    }
}
