using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Vdlcrm.Model;
using Vdlcrm.Model.DTOs;
using Vdlcrm.Services;

namespace Vdlcrm.Web.Controllers.Account;

[ApiController]
[Route("api/[controller]")]
[Authorize]
public class StudentController : ControllerBase
{
    private readonly StudentService _studentService;
    private readonly ILogger<StudentController> _logger;

    public StudentController(StudentService studentService, ILogger<StudentController> logger)
    {
        _studentService = studentService;
        _logger = logger;
    }

    /// <summary>
    /// Register a new student (Public endpoint)
    /// Auto-generates VDL ID (VDL001, VDL002, etc.)
    /// Creates user account with temporary password
    /// Thread-safe for concurrent bulk registrations
    /// </summary>
    /// <param name="request">Student registration details</param>
    /// <returns>Newly registered student with VDL ID, username, and temp password</returns>
    [HttpPost("register")]
    [AllowAnonymous]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<ActionResult<StudentRegistrationResponse>> RegisterStudent([FromBody] StudentRegisterRequest request)
    {
        if (request == null)
        {
            return BadRequest(new { message = "Student details cannot be null." });
        }

        // Map DTO to Student model. VdlId is intentionally left blank to be auto-generated by the service.
        var student = new Student
        {
            Name = request.Name,
            Email = request.Email,
            FatherName = request.FatherName,
            Gender = request.Gender,
            SeatNumber = request.SeatNumber,
            ShiftType = request.ShiftType,
            Address = request.Address,
            AlternateNumber = request.AlternateNumber,
            Class = request.Class,
            DateOfBirth = request.DateOfBirth,
            IdProof = request.IdProof,
            MobileNumber = request.MobileNumber,
            StudentStatus = string.IsNullOrWhiteSpace(request.StudentStatus) ? "Active" : request.StudentStatus,
            VdlId = "" // Handled by StudentService
        };

        try
        {
            _logger.LogInformation($"Processing student registration for email: {student.Email}");

            // Register student with auto-generated VDL ID and user account creation
            var (registeredStudent, userAccount, tempPassword) = await _studentService.RegisterStudentAsync(student);

            // Prepare response with temp password
            var response = new StudentRegistrationResponse
            {
                StudentId = registeredStudent.Id,
                VdlId = registeredStudent.VdlId,
                Name = registeredStudent.Name,
                Email = registeredStudent.Email,
                Username = userAccount.Username,
                TempPassword = tempPassword,  // Send temp password once to student
                RoleId = userAccount.RoleId,
                CreatedDate = registeredStudent.CreatedDate,
                Message = "Student registered successfully. Use the provided VDL ID, username, and temporary password to login."
            };

            _logger.LogInformation($"Student registration successful: VdlId={registeredStudent.VdlId}, Username={userAccount.Username}");

            return CreatedAtAction(nameof(GetStudentByVdlId), new { vdlId = registeredStudent.VdlId }, response);
        }
        catch (ArgumentException ex)
        {
            _logger.LogWarning($"Validation error during student registration: {ex.Message}");
            return BadRequest(new { message = ex.Message });
        }
        catch (DbUpdateException dbEx)
        {
            _logger.LogError($"Database conflict during student registration: {dbEx.Message}");
            return Conflict(new { message = "Student or email already exists. Please use different email.", error = dbEx.Message });
        }
        catch (InvalidOperationException ioEx)
        {
            _logger.LogError($"Operation error during student registration: {ioEx.Message}");
            return StatusCode(StatusCodes.Status500InternalServerError, 
                new { message = "Unable to complete registration. Please try again.", error = ioEx.Message });
        }
        catch (Exception ex)
        {
            _logger.LogError($"Unexpected error during student registration: {ex.Message}");
            return StatusCode(StatusCodes.Status500InternalServerError, 
                new { message = "An error occurred while registering the student.", error = ex.Message });
        }
    }

    /// <summary>
    /// Get all registered students (Admin and Internal User only)
    /// </summary>
    /// <returns>List of all students</returns>
    [HttpGet("/api/StudentList")]
    [Authorize(Roles = "Admin,Internal User")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<ActionResult<IEnumerable<Student>>> GetAllStudents()
    {
        try
        {
            var students = await _studentService.GetAllStudentsAsync();
            return Ok(students);
        }
        catch (Exception ex)
        {
            return StatusCode(StatusCodes.Status500InternalServerError,
                new { message = "An error occurred while retrieving students.", error = ex.Message });
        }
    }

    /// <summary>
    /// Get a student by VDL ID (Authorized users only)
    /// </summary>
    /// <param name="vdlId">Student VDL ID</param>
    /// <returns>Student details if found</returns>
    [HttpGet("{vdlId}")]
    [Authorize]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<ActionResult<Student>> GetStudentByVdlId(string vdlId)
    {
        if (string.IsNullOrWhiteSpace(vdlId))
        {
            return BadRequest(new { message = "VDL ID cannot be empty." });
        }

        try
        {
            var student = await _studentService.GetStudentByVdlIdAsync(vdlId);
            if (student == null)
            {
                return NotFound(new { message = $"Student with VDL ID '{vdlId}' not found." });
            }

            return Ok(student);
        }
        catch (Exception ex)
        {
            return StatusCode(StatusCodes.Status500InternalServerError,
                new { message = "An error occurred while retrieving the student.", error = ex.Message });
        }
    }

    /// <summary>
    /// Update student details (Admin only)
    /// </summary>
    /// <param name="vdlId">Student VDL ID</param>
    /// <param name="request">Updated student details</param>
    /// <returns>Updated student</returns>
    [HttpPut("{vdlId}")]
    [Authorize(Roles = "Admin")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<ActionResult<Student>> UpdateStudent(string vdlId, [FromBody] StudentUpdateRequest request)
    {
        if (string.IsNullOrWhiteSpace(vdlId) || request == null)
        {
            return BadRequest(new { message = "Invalid VDL ID or update request details." });
        }

        if (!string.Equals(request.VdlId, vdlId, StringComparison.OrdinalIgnoreCase))
        {
            return BadRequest(new { message = "VDL ID in URL does not match the VDL ID in the request body." });
        }

        try
        {
            var existingStudent = await _studentService.GetStudentByVdlIdAsync(vdlId);
            if (existingStudent == null)
            {
                return NotFound(new { message = $"Student with VDL ID '{vdlId}' not found." });
            }

            // Naye values ko existing student object me map karein
            existingStudent.Name = request.Name;
            existingStudent.Email = request.Email;
            existingStudent.FatherName = request.FatherName;
            existingStudent.Gender = request.Gender;
            existingStudent.SeatNumber = request.SeatNumber;
            existingStudent.ShiftType = request.ShiftType;
            existingStudent.Address = request.Address;
            existingStudent.AlternateNumber = request.AlternateNumber;
            existingStudent.Class = request.Class;
            existingStudent.DateOfBirth = request.DateOfBirth;
            existingStudent.IdProof = request.IdProof;
            existingStudent.MobileNumber = request.MobileNumber;
            existingStudent.StudentStatus = request.StudentStatus;

            // Id aur CreatedDate preserve ho jayenge, UpdatedDate service layer me modify hoga
            var updatedStudent = await _studentService.UpdateStudentAsync(existingStudent);
            return Ok(updatedStudent);
        }
        catch (ArgumentException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
        catch (Exception ex)
        {
            return StatusCode(StatusCodes.Status500InternalServerError,
                new { message = "An error occurred while updating the student.", error = ex.Message });
        }
    }

    /// <summary>
    /// Delete a student (Admin only)
    /// </summary>
    /// <param name="vdlId">Student VDL ID</param>
    /// <returns>Success message</returns>
    [HttpDelete("{vdlId}")]
    [Authorize(Roles = "Admin")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<ActionResult> DeleteStudent(string vdlId)
    {
        if (string.IsNullOrWhiteSpace(vdlId))
        {
            return BadRequest(new { message = "VDL ID cannot be empty." });
        }

        try
        {
            var deleted = await _studentService.DeleteStudentAsync(vdlId);
            if (!deleted)
            {
                return NotFound(new { message = $"Student with VDL ID '{vdlId}' not found." });
            }

            return Ok(new { message = $"Student with VDL ID '{vdlId}' has been successfully deleted." });
        }
        catch (Exception ex)
        {
            return StatusCode(StatusCodes.Status500InternalServerError,
                new { message = "An error occurred while deleting the student.", error = ex.Message });
        }
    }
}
