using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Vdlcrm.Model;
using Vdlcrm.Model.DTOs;
using Vdlcrm.Services;
using Vdlcrm.Model.Enums;
using System.Security.Claims;

namespace Vdlcrm.Web.Controllers.Account;

[ApiController]
[Route("api/[controller]")]
[Authorize]
public class StudentController : ControllerBase
{
    private readonly StudentService _studentService;
    private readonly ILogger<StudentController> _logger;
    private readonly ErrorLoggingService _errorLoggingService;
    private readonly AppDbContext _dbContext;

    public StudentController(StudentService studentService, ILogger<StudentController> logger, ErrorLoggingService errorLoggingService, AppDbContext dbContext)
    {
        _studentService = studentService;
        _logger = logger;
        _errorLoggingService = errorLoggingService;
        _dbContext = dbContext;
    }

    /// <summary>
    /// Register a new student (Public endpoint)
    /// Auto-generates VDL ID (VDL001, VDL002, etc.)
    /// Creates user account with temporary password
    /// Thread-safe for concurrent bulk registrations
    /// </summary>
    /// <param name="request">Student registration details</param>
    /// <returns>Newly registered student with VDL ID, username, and temp password</returns>
    [HttpPost("register")]
    [AllowAnonymous]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<ActionResult<StudentRegistrationResponse>> RegisterStudent([FromBody] StudentRegisterRequest request)
    {
        if (request == null)
        {
            return BadRequest(new { message = "Student details cannot be null." });
        }

        // Enums ka use karke status parse karna aur int as string set karne ka logic
        int initialStatus = (int)StudentStatusEnum.Active;
        if (!string.IsNullOrWhiteSpace(request.StudentStatus))
        {
            if (Enum.TryParse<StudentStatusEnum>(request.StudentStatus, true, out var parsedStatus))
            {
                initialStatus = (int)parsedStatus;
            }
            else if (int.TryParse(request.StudentStatus, out int parsedInt) && Enum.IsDefined(typeof(StudentStatusEnum), parsedInt))
            {
                initialStatus = parsedInt;
            }
        }

        var createdBy = User.Identity?.IsAuthenticated == true ? User.FindFirst(ClaimTypes.Name)?.Value : "self";

        // Map DTO to Student model. VdlId is intentionally left blank to be auto-generated by the service.
        var student = new Student
        {
            Name = request.Name,
            Email = request.Email,
            FatherName = request.FatherName,
            Gender = request.Gender,
            SeatNumber = request.SeatNumber,
            ShiftType = request.ShiftType,
            Address = request.Address,
            AlternateNumber = request.AlternateNumber,
            Class = request.Class,
            DateOfBirth = request.DateOfBirth,
            IdProof = request.IdProof,
            MobileNumber = request.MobileNumber,
            StudentStatus = initialStatus.ToString(), // Database me integer ki string representation store hogi
            CreatedBy = createdBy ?? "self",
            VdlId = "" // Handled by StudentService
        };

        try
        {
            _logger.LogInformation($"Processing student registration for email: {student.Email}");

            // Register student with auto-generated VDL ID and user account creation
            var (registeredStudent, userAccount, tempPassword) = await _studentService.RegisterStudentAsync(student);

            // Prepare response with temp password
            var response = new StudentRegistrationResponse
            {
                StudentId = registeredStudent.Id,
                VdlId = registeredStudent.VdlId,
                Name = registeredStudent.Name,
                Email = registeredStudent.Email,
                Username = userAccount.Username,
                TempPassword = tempPassword,  // Send temp password once to student
                RoleId = userAccount.RoleId,
                CreatedDate = registeredStudent.CreatedDate,
                Message = "Student registered successfully. Use the provided VDL ID, username, and temporary password to login."
            };

            _logger.LogInformation($"Student registration successful: VdlId={registeredStudent.VdlId}, Username={userAccount.Username}");

            return CreatedAtAction(nameof(GetStudentByVdlId), new { vdlId = registeredStudent.VdlId }, response);
        }
        catch (ArgumentException ex)
        {
            _logger.LogWarning($"Validation error during student registration: {ex.Message}");
            await _errorLoggingService.LogExceptionAsync(ex, HttpContext.Request.Path);
            return BadRequest(new { message = ex.Message });
        }
        catch (DbUpdateException dbEx)
        {
            _logger.LogError($"Database conflict during student registration: {dbEx.Message}");
            await _errorLoggingService.LogExceptionAsync(dbEx, HttpContext.Request.Path);
            return Conflict(new { message = "Student or email already exists. Please use different email.", error = dbEx.Message });
        }
        catch (InvalidOperationException ioEx)
        {
            _logger.LogError($"Operation error during student registration: {ioEx.Message}");
            await _errorLoggingService.LogExceptionAsync(ioEx, HttpContext.Request.Path);
            return StatusCode(StatusCodes.Status500InternalServerError, 
                new { message = "Unable to complete registration. Please try again.", error = ioEx.Message });
        }
        catch (Exception ex)
        {
            _logger.LogError($"Unexpected error during student registration: {ex.Message}");
            await _errorLoggingService.LogExceptionAsync(ex, HttpContext.Request.Path);
            return StatusCode(StatusCodes.Status500InternalServerError, 
                new { message = "An error occurred while registering the student.", error = ex.Message });
        }
    }

    /// <summary>
    /// Get all registered students (Admin and Internal User only)
    /// </summary>
    /// <returns>List of all students</returns>
    [HttpGet("list")]
    [Authorize] // 👈 Ab role Database se check hoga
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<ActionResult<IEnumerable<Student>>> GetAllStudents()
    {
        try
        {
            var students = (await _studentService.GetAllStudentsAsync()).ToList();

            // VDL ID aur Name ka lookup dictionary banayein (GroupBy ka use taaki duplicate records se exception na aaye)
            var nameLookup = students
                .Where(s => !string.IsNullOrWhiteSpace(s.VdlId))
                .GroupBy(s => s.VdlId, StringComparer.OrdinalIgnoreCase)
                .ToDictionary(g => g.Key, g => g.First().Name, StringComparer.OrdinalIgnoreCase);

            var vdlIds = students.Select(s => s.VdlId).ToList();
            
            // Sabhi students ki fees bulk me fetch karke har student ka latest status map karein (taaki N+1 query issue na ho)
            var feeRecords = await _dbContext.FeeRecords
                .Where(f => vdlIds.Contains(f.VdlId))
                .Select(f => new { 
                    f.Id, 
                    f.VdlId, 
                    f.Status, 
                    f.StartDate, 
                    f.EndDate, 
                    f.CreatedDate,
                    f.TotalFee,
                    TotalPaid = f.FeePayments.Sum(p => p.AmountPaid)
                })
                .ToListAsync();
            var latestFees = feeRecords.GroupBy(f => f.VdlId)
                .ToDictionary(g => g.Key, g => g.OrderByDescending(f => f.CreatedDate).First());

            // Users table se roles nikalna
            var userRolesList = await _dbContext.Users
                .Include(u => u.Role)
                .Where(u => vdlIds.Contains(u.Username))
                .Select(u => new { u.Username, u.RoleId, RoleName = u.Role != null ? u.Role.RoleName : "Student" })
                .ToListAsync();
            var userRoles = userRolesList.GroupBy(u => u.Username, StringComparer.OrdinalIgnoreCase)
                .ToDictionary(g => g.Key, g => g.First(), StringComparer.OrdinalIgnoreCase);

            foreach (var student in students)
            {
                if (!string.IsNullOrWhiteSpace(student.CreatedBy) && student.CreatedBy.ToLower() != "self")
                {
                    // Asal ID extract karein (agar pehle se hi ' - ' attached hai to usko ignore karein)
                    var originalCreatedBy = student.CreatedBy.Split(" - ")[0].Trim();
                    
                    if (nameLookup.TryGetValue(originalCreatedBy, out var creatorName) && !string.IsNullOrWhiteSpace(creatorName))
                    {
                        student.CreatedBy = $"{originalCreatedBy} - {creatorName}";
                    }
                }

                // Last Fee Status and Dates map karein
                if (latestFees.TryGetValue(student.VdlId, out var feeInfo))
                {
                    student.LastFeeStatus = feeInfo.Status.ToString();
                    student.LastFeeStartDate = feeInfo.StartDate;
                    student.LastFeeEndDate = feeInfo.EndDate;
                    student.LastFeeRecordId = feeInfo.Id;
                    student.RemainingBalance = feeInfo.TotalFee - feeInfo.TotalPaid;
                }
                else
                {
                    student.LastFeeStatus = "Not Available";
                }

                // Role map karein
                if (userRoles.TryGetValue(student.VdlId, out var roleInfo))
                {
                    student.RoleId = roleInfo.RoleId;
                    student.RoleName = roleInfo.RoleName;
                }
                else
                {
                    student.RoleId = 4;
                    student.RoleName = "Student";
                }
            }

            return Ok(students);
        }
        catch (Exception ex)
        {
            await _errorLoggingService.LogExceptionAsync(ex, HttpContext.Request.Path);
            return StatusCode(StatusCodes.Status500InternalServerError,
                new { message = "An error occurred while retrieving students.", error = ex.Message });
        }
    }

    /// <summary>
    /// Get a student by VDL ID (Authorized users only)
    /// </summary>
    /// <param name="vdlId">Student VDL ID</param>
    /// <returns>Student details if found</returns>
    [HttpGet("details/{vdlId}")]
    [Authorize]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<ActionResult<Student>> GetStudentByVdlId(string vdlId)
    {
        if (string.IsNullOrWhiteSpace(vdlId))
        {
            return BadRequest(new { message = "VDL ID cannot be empty." });
        }

        // Data-Level Security (Row-Level Security)
        // Ensure Role 4 (Student) can only view their own record
        var claimsIdentity = User.Identity as ClaimsIdentity;
        var roleIdClaim = claimsIdentity?.FindFirst("RoleId");
        var usernameClaim = claimsIdentity?.FindFirst(ClaimTypes.Name); // Username contains VDL ID
        
        if (int.TryParse(roleIdClaim?.Value, out int roleId))
        {
            if (roleId == 4) // Student Role
            {
                var tokenVdlId = usernameClaim?.Value;
                if (!string.Equals(vdlId, tokenVdlId, StringComparison.OrdinalIgnoreCase))
                {
                    return StatusCode(StatusCodes.Status403Forbidden, new { message = "Access Denied: You can only view your own details." });
                }
            }
        }

        try
        {
            var student = await _studentService.GetStudentByVdlIdAsync(vdlId);
            if (student == null)
            {
                return NotFound(new { message = $"Student with VDL ID '{vdlId}' not found." });
            }

            // Single student details get karte waqt bhi CreatedBy ko format karein
            if (!string.IsNullOrWhiteSpace(student.CreatedBy) && student.CreatedBy.ToLower() != "self")
            {
                var originalCreatedBy = student.CreatedBy.Split(" - ")[0].Trim();
                var creator = await _studentService.GetStudentByVdlIdAsync(originalCreatedBy);
                if (creator != null && !string.IsNullOrWhiteSpace(creator.Name))
                {
                    student.CreatedBy = $"{originalCreatedBy} - {creator.Name}";
                }
            }

            // Last Fee status and dates nikaalna 
            var latestFee = await _dbContext.FeeRecords
                .Where(f => f.VdlId == student.VdlId)
                .OrderByDescending(f => f.CreatedDate)
                .Select(f => new { 
                    f.Id, 
                    f.Status, 
                    f.StartDate, 
                    f.EndDate,
                    f.TotalFee,
                    TotalPaid = f.FeePayments.Sum(p => p.AmountPaid)
                })
                .FirstOrDefaultAsync();
            
            if (latestFee != null)
            {
                student.LastFeeStatus = latestFee.Status.ToString();
                student.LastFeeStartDate = latestFee.StartDate;
                student.LastFeeEndDate = latestFee.EndDate;
                student.LastFeeRecordId = latestFee.Id;
                student.RemainingBalance = latestFee.TotalFee - latestFee.TotalPaid;
            }
            else
            {
                student.LastFeeStatus = "Not Available";
            }

            // Role set karna
            var user = await _dbContext.Users.Include(u => u.Role).FirstOrDefaultAsync(u => u.Username == student.VdlId);
            student.RoleId = user?.RoleId ?? 4;
            student.RoleName = user?.Role?.RoleName ?? "Student";

            return Ok(student);
        }
        catch (Exception ex)
        {
            await _errorLoggingService.LogExceptionAsync(ex, HttpContext.Request.Path);
            return StatusCode(StatusCodes.Status500InternalServerError,
                new { message = "An error occurred while retrieving the student.", error = ex.Message });
        }
    }

    /// <summary>
    /// Update student details (Admin only)
    /// </summary>
    /// <param name="vdlId">Student VDL ID</param>
    /// <param name="request">Updated student details</param>
    /// <returns>Updated student</returns>
    [HttpPut("update/{vdlId}")]
    [Authorize] // 👈 Ab role Database se check hoga
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<ActionResult<Student>> UpdateStudent(string vdlId, [FromBody] StudentUpdateRequest request)
    {
        if (string.IsNullOrWhiteSpace(vdlId) || request == null)
        {
            return BadRequest(new { message = "Invalid VDL ID or update request details." });
        }

        if (!string.Equals(request.VdlId, vdlId, StringComparison.OrdinalIgnoreCase))
        {
            return BadRequest(new { message = "VDL ID in URL does not match the VDL ID in the request body." });
        }

        try
        {
            var existingStudent = await _studentService.GetStudentByVdlIdAsync(vdlId);
            if (existingStudent == null)
            {
                return NotFound(new { message = $"Student with VDL ID '{vdlId}' not found." });
            }

            // Naye values ko existing student object me map karein
            existingStudent.Name = request.Name;
            existingStudent.Email = request.Email;
            existingStudent.FatherName = request.FatherName;
            existingStudent.Gender = request.Gender;
            existingStudent.SeatNumber = request.SeatNumber;
            existingStudent.ShiftType = request.ShiftType;
            existingStudent.Address = request.Address;
            existingStudent.AlternateNumber = request.AlternateNumber;
            existingStudent.Class = request.Class;
            existingStudent.DateOfBirth = request.DateOfBirth;
            existingStudent.IdProof = request.IdProof;
            existingStudent.MobileNumber = request.MobileNumber;

            // Status ko update karte waqt Enum validate aur int-to-string conversion karna
            if (!string.IsNullOrWhiteSpace(request.StudentStatus))
            {
                if (Enum.TryParse<StudentStatusEnum>(request.StudentStatus, true, out var parsedStatus))
                {
                    existingStudent.StudentStatus = ((int)parsedStatus).ToString();
                }
                else if (int.TryParse(request.StudentStatus, out int parsedInt) && Enum.IsDefined(typeof(StudentStatusEnum), parsedInt))
                {
                    existingStudent.StudentStatus = parsedInt.ToString();
                }
            }

            // Id aur CreatedDate preserve ho jayenge, UpdatedDate service layer me modify hoga
            var updatedStudent = await _studentService.UpdateStudentAsync(existingStudent);
            
            // Update ke baad response format ko consistent rakhne ke liye mapping apply karein
            if (!string.IsNullOrWhiteSpace(updatedStudent.CreatedBy) && updatedStudent.CreatedBy.ToLower() != "self")
            {
                var originalCreatedBy = updatedStudent.CreatedBy.Split(" - ")[0].Trim();
                var creator = await _studentService.GetStudentByVdlIdAsync(originalCreatedBy);
                if (creator != null && !string.IsNullOrWhiteSpace(creator.Name))
                {
                    updatedStudent.CreatedBy = $"{originalCreatedBy} - {creator.Name}";
                }
            }

            // Last Fee status and dates set karna
            var latestFee = await _dbContext.FeeRecords
                .Where(f => f.VdlId == updatedStudent.VdlId)
                .OrderByDescending(f => f.CreatedDate)
                .Select(f => new { 
                    f.Id, 
                    f.Status, 
                    f.StartDate, 
                    f.EndDate,
                    f.TotalFee,
                    TotalPaid = f.FeePayments.Sum(p => p.AmountPaid)
                })
                .FirstOrDefaultAsync();

            if (latestFee != null)
            {
                updatedStudent.LastFeeStatus = latestFee.Status.ToString();
                updatedStudent.LastFeeStartDate = latestFee.StartDate;
                updatedStudent.LastFeeEndDate = latestFee.EndDate;
                updatedStudent.LastFeeRecordId = latestFee.Id;
                updatedStudent.RemainingBalance = latestFee.TotalFee - latestFee.TotalPaid;
            }
            else
            {
                updatedStudent.LastFeeStatus = "Not Available";
            }

            // Role set karna
            var user = await _dbContext.Users.Include(u => u.Role).FirstOrDefaultAsync(u => u.Username == updatedStudent.VdlId);
            updatedStudent.RoleId = user?.RoleId ?? 4;
            updatedStudent.RoleName = user?.Role?.RoleName ?? "Student";

            return Ok(updatedStudent);
        }
        catch (ArgumentException ex)
        {
            await _errorLoggingService.LogExceptionAsync(ex, HttpContext.Request.Path);
            return BadRequest(new { message = ex.Message });
        }
        catch (Exception ex)
        {
            await _errorLoggingService.LogExceptionAsync(ex, HttpContext.Request.Path);
            return StatusCode(StatusCodes.Status500InternalServerError,
                new { message = "An error occurred while updating the student.", error = ex.Message });
        }
    }

    /// <summary>
    /// Delete a student (Admin only)
    /// </summary>
    /// <param name="vdlId">Student VDL ID</param>
    /// <returns>Success message</returns>
    [HttpDelete("delete/{vdlId}")]
    [Authorize] // 👈 Ab role Database se check hoga
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<ActionResult> DeleteStudent(string vdlId)
    {
        if (string.IsNullOrWhiteSpace(vdlId))
        {
            return BadRequest(new { message = "VDL ID cannot be empty." });
        }

        try
        {
            var deleted = await _studentService.DeleteStudentByVdlIdAsync(vdlId);
            if (!deleted)
            {
                return NotFound(new { message = $"Student with VDL ID '{vdlId}' not found." });
            }

            return Ok(new { message = $"Student with VDL ID '{vdlId}' has been successfully deleted." });
        }
        catch (Exception ex)
        {
            await _errorLoggingService.LogExceptionAsync(ex, HttpContext.Request.Path);
            return StatusCode(StatusCodes.Status500InternalServerError,
                new { message = "An error occurred while deleting the student.", error = ex.Message });
        }
    }
}
